# Generated by Django 5.2.10 on 2026-01-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='auth_header_name',
            field=models.CharField(default='X-API-Key', max_length=100),
        ),
    ]
