# Generated by Django 5.2.10 on 2026-01-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('requests_per_minute', models.IntegerField()),
                ('requests_per_month', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
